### ISSUE TITLE
Problem in executing example file in pyAT

### ISSUE THREAD

**Issue by surajrrcat** [willrogers/k3sbl#1]
Dear Sir,

I am new to python as well as pyAT. I have used AT in MATLAB. Now I am trying to use pyAT in python. I followed the path for the installation of pyAT on python 3.8. It successfully imports at. But at the section of creating the ring. It shows an error. It shows no such file in the directory. Please help me. 
Also, can you give more examples of how to use pyAT.

**Comment by willrogers** [comment]
Hi,

This is a strange place to ask this question. Please ask here: https://github.com/atcollab/at/issues.

Cheers,
Will
